export const dashboardV2Data = {
  overview: {
    totalUsers: 12450,
    totalRevenue: 2350000,
    activeProjects: 48,
    completionRate: 87,
  },
  charts: {
    salesData: [
      { month: 'Jan', sales: 4000, target: 3800 },
      { month: 'Feb', sales: 3000, target: 3200 },
      { month: 'Mar', sales: 5000, target: 4500 },
      { month: 'Apr', sales: 4500, target: 4200 },
      { month: 'May', sales: 6000, target: 5500 },
      { month: 'Jun', sales: 5500, target: 5200 },
    ],
    performanceData: [
      { name: 'Development', value: 400, color: '#0088FE' },
      { name: 'Testing', value: 300, color: '#00C49F' },
      { name: 'Deployment', value: 200, color: '#FFBB28' },
      { name: 'Maintenance', value: 100, color: '#FF8042' },
    ],
    trendData: Array.from({ length: 30 }, (_, i) => ({
      day: i + 1,
      value: Math.floor(Math.random() * 100) + 50,
    })),
  },
  recentActivities: [
    {
      id: 1,
      title: 'System Update Completed',
      description: 'Backend infrastructure updated successfully',
      timestamp: '2 hours ago',
      type: 'success',
    },
    {
      id: 2,
      title: 'New User Registration',
      description: '25 new users registered today',
      timestamp: '4 hours ago',
      type: 'info',
    },
    {
      id: 3,
      title: 'Security Scan Alert',
      description: 'Routine security scan detected minor issues',
      timestamp: '6 hours ago',
      type: 'warning',
    },
    {
      id: 4,
      title: 'Backup Completed',
      description: 'Daily database backup completed successfully',
      timestamp: '8 hours ago',
      type: 'success',
    },
    {
      id: 5,
      title: 'API Rate Limit Exceeded',
      description: 'Third-party API calls exceeded daily limit',
      timestamp: '10 hours ago',
      type: 'error',
    },
    {
      id: 6,
      title: 'Deployment Successful',
      description: 'Version 2.1.4 deployed to production environment',
      timestamp: '12 hours ago',
      type: 'success',
    },
    {
      id: 7,
      title: 'Performance Alert',
      description: 'Database response time increased above threshold',
      timestamp: '14 hours ago',
      type: 'warning',
    },
    {
      id: 8,
      title: 'User Feedback Received',
      description: 'New feature feedback from 15 beta users',
      timestamp: '16 hours ago',
      type: 'info',
    },
    {
      id: 9,
      title: 'SSL Certificate Renewed',
      description: 'Production SSL certificates updated successfully',
      timestamp: '18 hours ago',
      type: 'success',
    },
    {
      id: 10,
      title: 'Memory Usage Warning',
      description: 'Server memory usage reached 85% capacity',
      timestamp: '20 hours ago',
      type: 'warning',
    },
    {
      id: 11,
      title: 'Code Review Completed',
      description: 'Pull request #247 approved and merged',
      timestamp: '22 hours ago',
      type: 'success',
    },
    {
      id: 12,
      title: 'Service Outage Detected',
      description: 'Payment service experienced 5 minute downtime',
      timestamp: '1 day ago',
      type: 'error',
    },
    {
      id: 13,
      title: 'Cache Optimization',
      description: 'Redis cache performance improved by 30%',
      timestamp: '1 day ago',
      type: 'info',
    },
    {
      id: 14,
      title: 'Team Meeting Scheduled',
      description: 'Sprint planning meeting set for tomorrow 9 AM',
      timestamp: '1 day ago',
      type: 'info',
    },
    {
      id: 15,
      title: 'Load Balancer Updated',
      description: 'Traffic distribution rules optimized',
      timestamp: '1 day ago',
      type: 'success',
    },
    {
      id: 16,
      title: 'Database Migration Alert',
      description: 'Scheduled maintenance requires temporary read-only mode',
      timestamp: '2 days ago',
      type: 'warning',
    },
    {
      id: 17,
      title: 'Feature Flag Enabled',
      description: 'Dark mode feature rolled out to 50% of users',
      timestamp: '2 days ago',
      type: 'info',
    },
    {
      id: 18,
      title: 'Monitoring Alert Resolved',
      description: 'Network latency issue automatically resolved',
      timestamp: '2 days ago',
      type: 'success',
    },
    {
      id: 19,
      title: 'Security Patch Applied',
      description: 'Critical vulnerability fixed in authentication module',
      timestamp: '3 days ago',
      type: 'success',
    },
    {
      id: 20,
      title: 'Docker Container Updated',
      description: 'All microservices updated to latest container images',
      timestamp: '3 days ago',
      type: 'info',
    },
    {
      id: 21,
      title: 'File Upload Limit Exceeded',
      description: 'User attempted to upload 500MB file, exceeding 100MB limit',
      timestamp: '3 days ago',
      type: 'error',
    },
    {
      id: 22,
      title: 'Automated Testing Passed',
      description: 'All 847 unit tests passed in CI/CD pipeline',
      timestamp: '4 days ago',
      type: 'success',
    },
    {
      id: 23,
      title: 'CDN Cache Cleared',
      description: 'Global CDN cache cleared for static assets update',
      timestamp: '4 days ago',
      type: 'info',
    },
    {
      id: 24,
      title: 'Email Service Disruption',
      description:
        'SMTP server was down for 15 minutes, affecting notifications',
      timestamp: '4 days ago',
      type: 'error',
    },
    {
      id: 25,
      title: 'New Employee Access Granted',
      description: 'John Smith granted developer access to staging environment',
      timestamp: '5 days ago',
      type: 'info',
    },
    {
      id: 26,
      title: 'Storage Cleanup Completed',
      description: 'Deleted 2.5GB of old log files and temporary data',
      timestamp: '5 days ago',
      type: 'success',
    },
    {
      id: 27,
      title: 'API Version Deprecated',
      description: 'API v1.2 deprecated, migration to v2.0 required by January',
      timestamp: '5 days ago',
      type: 'warning',
    },
    {
      id: 28,
      title: 'User Session Timeout',
      description: 'Session timeout reduced from 24h to 8h for security',
      timestamp: '6 days ago',
      type: 'info',
    },
    {
      id: 29,
      title: 'Branch Protection Enabled',
      description: 'Main branch now requires 2 approvals before merge',
      timestamp: '6 days ago',
      type: 'success',
    },
    {
      id: 30,
      title: 'Webhook Failure Detected',
      description: 'Payment webhook failed 3 times, manual verification needed',
      timestamp: '6 days ago',
      type: 'error',
    },
    {
      id: 31,
      title: 'Analytics Report Generated',
      description: 'Weekly user engagement report available in admin panel',
      timestamp: '1 week ago',
      type: 'info',
    },
    {
      id: 32,
      title: 'Password Policy Updated',
      description: 'Minimum password length increased to 12 characters',
      timestamp: '1 week ago',
      type: 'warning',
    },
    {
      id: 33,
      title: 'Third-party Integration Success',
      description: 'Salesforce integration completed and tested successfully',
      timestamp: '1 week ago',
      type: 'success',
    },
    {
      id: 34,
      title: 'Scheduled Maintenance Window',
      description: 'System maintenance completed 30 minutes ahead of schedule',
      timestamp: '1 week ago',
      type: 'success',
    },
  ],
  projectStatus: [
    {
      id: 1,
      name: 'E-commerce Platform',
      progress: 85,
      status: 'In Progress',
      team: 'Frontend Team',
      deadline: '2024-12-15',
    },
    {
      id: 2,
      name: 'Mobile App Redesign',
      progress: 60,
      status: 'In Progress',
      team: 'Design Team',
      deadline: '2024-11-30',
    },
    {
      id: 3,
      name: 'API Gateway Migration',
      progress: 100,
      status: 'Completed',
      team: 'Backend Team',
      deadline: '2024-10-20',
    },
    {
      id: 4,
      name: 'Analytics Dashboard',
      progress: 45,
      status: 'Planning',
      team: 'Data Team',
      deadline: '2025-01-15',
    },
    {
      id: 5,
      name: 'Customer Portal V2',
      progress: 75,
      status: 'In Progress',
      team: 'Full Stack Team',
      deadline: '2024-12-30',
    },
    {
      id: 6,
      name: 'Payment Gateway Integration',
      progress: 90,
      status: 'Testing',
      team: 'Backend Team',
      deadline: '2024-11-25',
    },
    {
      id: 7,
      name: 'Security Audit Framework',
      progress: 30,
      status: 'Planning',
      team: 'Security Team',
      deadline: '2025-02-15',
    },
    {
      id: 8,
      name: 'Machine Learning Pipeline',
      progress: 55,
      status: 'In Progress',
      team: 'AI/ML Team',
      deadline: '2025-01-30',
    },
    {
      id: 9,
      name: 'DevOps Automation',
      progress: 80,
      status: 'In Progress',
      team: 'DevOps Team',
      deadline: '2024-12-10',
    },
    {
      id: 10,
      name: 'Legacy System Migration',
      progress: 25,
      status: 'Planning',
      team: 'Infrastructure Team',
      deadline: '2025-03-20',
    },
    {
      id: 11,
      name: 'Real-time Chat Feature',
      progress: 95,
      status: 'Testing',
      team: 'Frontend Team',
      deadline: '2024-11-20',
    },
    {
      id: 12,
      name: 'Data Warehouse Optimization',
      progress: 40,
      status: 'In Progress',
      team: 'Data Engineering',
      deadline: '2025-01-25',
    },
    {
      id: 13,
      name: 'Mobile Push Notifications',
      progress: 70,
      status: 'In Progress',
      team: 'Mobile Team',
      deadline: '2024-12-05',
    },
    {
      id: 14,
      name: 'Cloud Infrastructure Upgrade',
      progress: 100,
      status: 'Completed',
      team: 'Cloud Team',
      deadline: '2024-10-15',
    },
    {
      id: 15,
      name: 'User Authentication Redesign',
      progress: 65,
      status: 'In Progress',
      team: 'Security Team',
      deadline: '2024-12-20',
    },
    {
      id: 16,
      name: 'Performance Monitoring Dashboard',
      progress: 35,
      status: 'Planning',
      team: 'DevOps Team',
      deadline: '2025-02-10',
    },
    {
      id: 17,
      name: 'Content Management System',
      progress: 50,
      status: 'In Progress',
      team: 'Backend Team',
      deadline: '2025-01-10',
    },
    {
      id: 18,
      name: 'Third-party API Integration',
      progress: 85,
      status: 'Testing',
      team: 'Integration Team',
      deadline: '2024-11-28',
    },
    {
      id: 19,
      name: 'Accessibility Compliance Update',
      progress: 20,
      status: 'Planning',
      team: 'Frontend Team',
      deadline: '2025-02-28',
    },
  ],
  notifications: [
    {
      id: 1,
      message: 'Server maintenance scheduled for tonight',
      priority: 'high',
      read: false,
    },
    {
      id: 2,
      message: 'Monthly report is ready for review',
      priority: 'medium',
      read: false,
    },
    {
      id: 3,
      message: 'New team member onboarded',
      priority: 'low',
      read: true,
    },
  ],
};
